In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [1]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [2]:
print(sent)

['the glass of milk', 'the glass of juice', 'the cup of tea', 'I am a good boy', 'I am a good developer', 'understand the meaning of words', 'your videos are good']


In [3]:
voc_size=10000


In [4]:
one_hot_repr= [one_hot(words,voc_size)for words in sent]
one_hot_repr

NameError: name 'one_hot' is not defined

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences 
from tensorflow.keras.models import Sequential

# from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences  # Correct import
# from tensorflow.keras.models import Sequential


In [ ]:

import numpy as np


In [ ]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr, padding="pre", maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9097 8153 7611 1211]
 [   0    0    0    0 9097 8153 7611  474]
 [   0    0    0    0 9097 9533 7611 4529]
 [   0    0    0 7358 2347 8544 2173 4118]
 [   0    0    0 7358 2347 8544 2173 7625]
 [   0    0    0 8922 9097 1841 7611 9148]
 [   0    0    0    0 7137 2516 3034 2173]]


In [ ]:
## feature representation
dim =10


In [ ]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\mouza\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step


array([[[ 4.9833070e-02,  1.0725379e-02, -3.9804269e-02,  3.2341573e-02,
          5.6935176e-03, -3.2552578e-02,  3.7951957e-02,  4.7669638e-02,
         -3.0140961e-02, -4.0385842e-02],
        [ 4.9833070e-02,  1.0725379e-02, -3.9804269e-02,  3.2341573e-02,
          5.6935176e-03, -3.2552578e-02,  3.7951957e-02,  4.7669638e-02,
         -3.0140961e-02, -4.0385842e-02],
        [ 4.9833070e-02,  1.0725379e-02, -3.9804269e-02,  3.2341573e-02,
          5.6935176e-03, -3.2552578e-02,  3.7951957e-02,  4.7669638e-02,
         -3.0140961e-02, -4.0385842e-02],
        [ 4.9833070e-02,  1.0725379e-02, -3.9804269e-02,  3.2341573e-02,
          5.6935176e-03, -3.2552578e-02,  3.7951957e-02,  4.7669638e-02,
         -3.0140961e-02, -4.0385842e-02],
        [ 1.2987066e-02, -1.6190957e-02,  3.9219271e-02, -3.6690593e-02,
          1.0548484e-02,  2.7137961e-02, -4.5329034e-02, -2.8514195e-02,
          3.9378788e-02, -2.7748719e-03],
        [ 3.6775496e-02, -3.4746312e-02,  1.5174713e-02,  2.